- .flake8
- azure-pipelines.yml
The test are using tox but the package was not installed.
> fix Azure pipelines testing - install tox

- src/aiohabit/actions/destroy.py
- src/aiohabit/actions/up.py
- src/aiohabit/config.py
- src/aiohabit/errors.py
- src/aiohabit/host.py
- src/aiohabit/providers/openstack.py
- src/aiohabit/run.py
- src/aiohabit/transformers/openstack.py
- src/aiohabit/transformers/transformer.py
- src/aiohabit/utils.py
Finishing of previous "WIP" architecture commit. With this, provisioning in OpenStack is working. I.e. machines can be provisioned by up action and destroyed by destroy action with state saved using File driver.
So that nice error message is shown on expected errors.
> make "up" and "destroy" action work + exception handling and fixing of some typos

- src/aiohabit/__init__.py
- src/aiohabit/actions/destroy.py
- src/aiohabit/actions/list.py
- src/aiohabit/actions/output.py
- src/aiohabit/actions/ssh.py
- src/aiohabit/actions/up.py
- src/aiohabit/providers/__init__.py
- src/aiohabit/providers/aws.py
- src/aiohabit/providers/openstack.py
- src/aiohabit/run.py
- src/aiohabit/transformers/__init__.py
- src/aiohabit/transformers/openstack.py
- src/aiohabit/utils.py
Configure a logger to be used in the whole application.
---
Based on the table [here](https://docs.python.org/3/howto/logging.html#when-to-use-logging, I wonder if we should keep all the prints for stdout and stderr messages instead of replacing them.
> Add basic logging mechanism

- Makefile
- azure-pipelines.yml
- pyproject.toml
- src/mrack/actions/destroy.py
- src/mrack/actions/ssh.py
- src/mrack/actions/up.py
- src/mrack/dbdrivers/file.py
- src/mrack/host.py
- src/mrack/outputs/ansible_inventory.py
- src/mrack/outputs/pytest_multihost.py
- src/mrack/providers/aws.py
- src/mrack/providers/openstack.py
- src/mrack/providers/static.py
- src/mrack/run.py
- src/mrack/transformers/__init__.py
- src/mrack/transformers/openstack.py
- src/mrack/transformers/static.py
- src/mrack/transformers/transformer.py
- src/mrack/utils.py
- tests/unit/test_openstack.py
Helper tool to sort the imports for us.
> Enable isort linting

- MANIFEST.in
- azure-pipelines.yml
- docs/conf.py
- setup.py
- test-requirements.txt
- tox.ini
Load the content of requirements.txt file
instead of having static list in setup.py
Resolves https://github.com/pvoborni/mrack/issues/15 
> Load the requirements.txt in setup.py

- tests/integration/conftest.py
- tests/integration/data/metadata-hosts.yaml
- tests/integration/data/provisioning-config.yaml
- tests/integration/test_actions.py
Testing up, output, list and destroy actions using the Static Provider.
> Add test scenario for actions with static provider

- tests/integration/test_actions.py
Latest version of black was complaing about these changes.
Previous version: black-19.10b0
Latest version: black-20.8b1
> Fix style after black update

- README.md
- docs/conf.py
- setup.py
- mrack now generates output with modules for:
ansible-inventory
pytest-multihost
- implemented static provider to create resource from static VMs
- added tests for static provider
- list and ssh actions
- added some minor fixes
> Release version 0.1.2

- azure-pipelines.yml
- requirements.txt
- src/mrack/providers/beaker.py
- src/mrack/run.py
- src/mrack/transformers/__init__.py
- src/mrack/transformers/beaker.py
> Add beaker provider

- docs/conf.py
- setup.py
New features:
Beaker provider support
Bug fixing and testing:
Use public AWS addresses
Remove asserts and replace them with ProvisioningErrors
> Release version 0.1.3

- docs/conf.py
- setup.py
Bug fixing and testing:
Fixed username for beaker machines to be root.
> Release version 0.1.4

- src/mrack/providers/beaker.py
> Add missing beaker job status

- docs/conf.py
- setup.py
Bug fixing and testing:
Refactor providers to share same code
Force black version to get rid of test errors
Remove false warnings produced by isort
Add missing beaker job status
ansible-inventory: rework generation of groups
> Release version 0.2.0

- docs/conf.py
- setup.py
New features:
Create CODE_OF_CONDUCT.md
Add basic image validation to AWS and Beaker
Support restraint_id record in metadata
Add docs on how to set credentials
Build and publish html to Azure artifacts storage
Bug Fixing and testing:
docs: set master doc to index
Remove missing and unused print_basic_info method
Fix destroy action because delete host now needs only host.id
Require specific versions for mrack
Fix regression in up action with OpenStack provider
Remove unused values in aws and beaker tranformation
> Release version 0.3.0

- src/mrack/__init__.py
- src/mrack/providers/aws.py
- src/mrack/providers/beaker.py
- src/mrack/providers/openstack.py
- src/mrack/providers/provider.py
- src/mrack/transformers/aws.py
- src/mrack/transformers/beaker.py
- src/mrack/transformers/openstack.py
- src/mrack/transformers/transformer.py
refactor: Add dsp_name to logging messages to display context
Add dsp_name to logging messages to display context
for prioviders and transformers.
Added some debug messages.
Aims to resolve https://github.com/neoave/mrack/issues/23 
> Improve mrack logging

- README.md
Update README.md file with sections:
where example inventory output is shown
where usage of the mrack is explained
> refactor: Update README.md file

- src/mrack/outputs/pytest_multihost.py
Commit 7bb230e170ac0a2373a2316ef23a26bfcb681ad9 removed setting of
users as it did not work "well" for Linux host in our testing. But
it broke assumtion that Windows host have it set. So this is a fix
to be compatible with our previous mechanism.
I'd call it a hotfix as it is needed but not great. It would be
better to have a more general mechanism with a degree of configuration
to make it adjustable for a project.
> fix: Set user for Windows host in pytest-multihost config

- .pre-commit-config.yaml
- .pylintrc
- scripts/mrack
- setup.py
- src/mrack/actions/destroy.py
- src/mrack/actions/etchosts.py
- src/mrack/actions/ssh.py
- src/mrack/actions/up.py
- src/mrack/config.py
- src/mrack/dbdrivers/file.py
- src/mrack/host.py
- src/mrack/outputs/ansible_inventory.py
- src/mrack/outputs/pytest_multihost.py
- src/mrack/outputs/utils.py
- src/mrack/providers/aws.py
- src/mrack/providers/beaker.py
- src/mrack/providers/openstack.py
- src/mrack/providers/podman.py
- src/mrack/providers/provider.py
- src/mrack/providers/static.py
- src/mrack/providers/utils/podman.py
- src/mrack/run.py
- src/mrack/transformers/openstack.py
- src/mrack/transformers/podman.py
- src/mrack/transformers/static.py
- src/mrack/transformers/transformer.py
- src/mrack/utils.py
- tests/unit/test_ansible_inventory.py
- tests/unit/test_etchosts.py
Use pylint in pre-commit-hook and actions as well to check code for easy to overlook mistakes.
Fix pylint isssues in mrack project
> chore: Add pylint to pre-commit-config.yaml and fix its issues in mrack

- src/mrack/providers/provider.py
handle TIMEDOUT state and treat it as an error 
Aims to resolve https://github.com/neoave/mrack/issues/79
> fix: treat timeouted machine as an error

- README.md
> docs: Add copr build badge and fix some typos

- README.md
Packages availble as rpm for Fedora 32+
> docs: Add info on how to install on Fedora

- .pylintrc
> chore: accept code which has 10 lines or less similar

- .github/workflows/pre-commit.yml
- .github/workflows/test-and-release.yml
> chore: Update GH workflows pre-commit version

- src/mrack/providers/provider.py
Let us fix that insanity I created please.
do not wait 1200/600 minutes for VM
> fix: decrease and insanely long timeout

- src/mrack/transformers/openstack.py
Currenlty Mrack always chooses a network with the most available IPs.
This is good for a lot of use cases but is problematic when a lot of jobs are started at the same time. Each of the jobs is doing a
separate network availability check. This can lead to a situation where almost all jobs pick the same and start provisioning with it.
But this network might not have enough IPs for everything so there is a increased chance that it will fail. E.g if there is 300 available IPs and we run 100 jobs which needs 3-4 machines.
Indroducing a new behavior where Mrack is picking a random network from networks which have at least 50% of IPs as the bests one. Thus spreading the load and lowering the chance of the issue to happening.
It will not solve the issue completely. This can be improved e.g. in …
> feat(OpenStack): distribute choosing of networks

- src/mrack/providers/provider.py
- src/mrack/transformers/openstack.py
- src/mrack/utils.py
These changes allows us to use older behavior with only changin provisioning-config.yaml file.
> feat: Add capability to disable ssh check in provisioning-config.yaml and update prio of hardcoded Administrator user

- src/mrack/providers/openstack.py
This PR is trivial what is more interesting I see this message on many places when looking at destroy action.
> refactor: Fix typo in log message

- src/mrack/transformers/transformer.py
feat: Support size definition in metadata
> feat: Support size definition in metadata

- .github/workflows/test-and-release.yml
> chore: Add f-trivino as release actor

- src/mrack/providers/aws.py
- src/mrack/providers/beaker.py
- src/mrack/providers/openstack.py
- src/mrack/providers/podman.py
- src/mrack/providers/provider.py
- src/mrack/providers/static.py
- src/mrack/providers/virt.py
> fix: Unite providers' create server to return tuple

- docs/guides/strategy.rst
- src/mrack/providers/static.py
- src/mrack/transformers/static.py
fix: make static provider more verbose
docs: fix title underline too short
> docs: fix the underline and verbosity of provider

- src/mrack/providers/beaker.py
> fix: add missing '/' to log message while deleting

- src/mrack/providers/beaker.py
- src/mrack/providers/openstack.py
- src/mrack/utils.py
add verbosity to beaker ssh and openstack plus increase poll sleep time for beaker
> feat: add verbosity and increase poll sleep time for beaker

- src/mrack/providers/aws.py
When we are missing export for AWS_CONFIG_FILE=...
boto throws an exception which we need to catch and
notify user nice way.
> fix(AWS): Catch traceback when credentials are missing

- src/mrack/providers/openstack.py
Can provision method was using only preloaded limits which caused
provisioning to fail always when resources at begining of the run
were already full. Now we reload limits with every can_provision()
method call and make sure load is refreshed and provisioning continues
> feat(Openstack): poll openstack load when running can_provision()

- src/mrack/data/provisioning-config.yaml
- src/mrack/providers/aws.py
- src/mrack/transformers/aws.py
The behavior is default it can be disabled by setting:
```
delete_volume_on_termination: false
```
In a config hierarchy of AWS provider.
> feat(aws): delete volumes on termination

- src/mrack/providers/aws.py
[feat(AWS): Create unique instance name with the tag]
Create unique instance Hostname tag which is used
or can be used by lambda functions on AWS to create
dynamic DNS records on the fly
[feat: Wait for the DNS record for up to 5 minutes]
> feat(AWS): Name tags and Hostname creation

- src/mrack/providers/beaker.py
Beaker was too chatty in console output so we moved the messages to the debug level so it is logged in the mrack.log only. Added debug message to the
function responsible for polling beaker for job status.
> fix: Beaker log polling to logfile instead of console

- src/mrack/providers/beaker.py
> fix(Beaker): Do not throw an Exception when not authenticated

- setup.py
- src/mrack/run.py
Change a code bit to support future mrack division to multiple packages
> feat: Support package splitting in the mrack

- src/mrack/providers/aws.py
> refactor: fix the typos in aws provider

- src/mrack/providers/beaker.py
mrack was failing with an exception when
Beaker hub was not replying to requests for
some time. With this we accept the fact that
hub may not respond and we use previous
result and continue the wait for resource.
> fix(Beaker): connection to hub timing out

- .github/workflows/check-commits.yml
- .github/workflows/pre-commit.yml
- README.md
- azure-pipelines.yml
- pyproject.toml
> chore: Use branch main instead of master

- MANIFEST.in
- mrack.spec
Update the mrack specfile to match fedora packaging standars and to move this project to official fedora packages via: https://bugzilla.redhat.com/show_bug.cgi?id=2134387
> fix: Update spec to match fedora community standard

- src/mrack/providers/openstack.py
- tests/unit/test_openstack.py
this is only renaming the method names and extracted subset of commits from https://github.com/neoave/mrack/pull/229
> refactor(OpenStack): refactor openstack method names

- src/mrack/config.py
- src/mrack/providers/provider.py
Latest release has a regression in MrackConfig caused by misconfiguration of tests before release internal tests are in progress containing this fix.
> fix(MrackConfig): Fix MrackConfig class properties

- README.md
> refactor: Update supported providers

- src/mrack/providers/openstack.py
one more await is missing for this method so fixing it.
> fix(OpenStack): Add missing await for self._load_limits() method call

- src/mrack/providers/aws.py
> refactor(AWS): change variable name typo in get_ip_addresses

- src/mrack/providers/openstack.py
- tests/unit/test_openstack.py
Fixing code block in `_opentack_gather_responses` method to avoid RuntimeError when a coroutine is reused in the loop.
Including a unit test for this method as part of the commit.
The issue was that a coroutine (aka the async function calls parameters) cannot be reused with await or gather, hence when a ServerError exception was raised, it caused a RunTime error. A workarround for this is awaiting using tasks instead of couroutines directly, and recreate the tasks if necessary to call the coroutines again.
> fix: Replace coroutines with tasks to avoid RuntimeError

- src/mrack/providers/provider.py
Since I have coded a regression when trying to re-provision
mrack is not setting variables for another loop correctly
error_hosts is updated correctly but when keeping success_hosts
not changed to empty list it creates a illusion of hosts
which were deleted because of re-provisioning strategy
that they are still up and running.
> fix: empty the success hosts and correctly set missing_reqs

- src/mrack/providers/provider.py
- tests/unit/test_openstack.py
- tests/unit/test_provider.py
> test: Add missing tests for recent fixes and features

- .packit.yaml
In case of any questions, please contact [Packit team](https://packit.dev/#contact).
For details, please see the commit messages.
> chore(Packit): Update Packit configuration

- docs/guides/beaker_hostRequires.rst
- docs/guides/index.rst
Add hostRequires documentation section to guides
> docs(Beaker): Add hostRequires documentation section to guides

- src/mrack/providers/beaker.py
- tests/unit/test_utils.py
Exception has been thrown as raise missed argument
> fix(Beaker): Exception has been thrown as raise missed argument

- .github/workflows/test-and-release.yml
- CHANGELOG.md
- mrack.spec
From issue: https://github.com/neoave/mrack/issues/269
> fix: broken command print version in semantic release

- .packit.yaml
Until secret injection issue into test farm is solved
> chore(ci): Temporarely remove packit tests

- src/mrack/utils.py
- tests/unit/test_utils.py
fix this issue:https://github.com/neoave/mrack/issues/291 :)
> feat: handle list value for add_dict_to_node function

- requirements.txt
fixes https://github.com/neoave/mrack/issues/317 introduced by https://github.com/neoave/mrack/pull/312
> fix: Enforce beaker-client 29.2 to fix fetch_url error
