neoave/mrack

scripts/aiohabit
setup.py
src/aiohabit/actions/__init__.py
src/aiohabit/actions/destroy.py
src/aiohabit/actions/up.py
src/aiohabit/dbdrivers/__init__.py
src/aiohabit/dbdrivers/file.py
src/aiohabit/errors.py
src/aiohabit/host.py
src/aiohabit/outputs/__init__.py
src/aiohabit/providers/__init__.py
src/aiohabit/providers/openstack.py
src/aiohabit/providers/provider.py
src/aiohabit/run.py
src/aiohabit/transformers/__init__.py
src/aiohabit/transformers/openstack.py
src/aiohabit/transformers/transformer.py
src/aiohabit/utils.py

Adding:
- up action
- destroy action
Introducing concepts:
Trasnsformers: combines metadata together with provisioning config to
get configuration for providers.
Outputs: transform result of providers to various files like ansible
inventory or pytest-multihost config
Drivers: saves results of actions to file so that it can be used
later. E.g. up action result to be used for destroy action.
Adds basic CLI entry point for debugging or standalone usage.

WIP: Main app architecture with basic functionality

---

requirements.txt
src/aiohabit/dbdrivers/file.py
src/aiohabit/providers/openstack.py
src/aiohabit/run.py
src/aiohabit/utils.py

Fixing:
db_driver.load() to take no params as the path is handled in init
ctx object should have ctx.obj to be accessed with key
Adding:
requirements were missing when installing in clear environment
yaml lib helper functions

Minor fixes to the sources and requirements

---

src/aiohabit/actions/output.py
src/aiohabit/host.py
src/aiohabit/outputs/ansible_inventory.py
src/aiohabit/outputs/pytest_multihost.py
src/aiohabit/outputs/utils.py
src/aiohabit/run.py
src/aiohabit/utils.py

And enhance "up" action to use them. Add also "output" action which  calls them separately. It can be used for recreation of deleted ones  or testing.
So that they can be work with in output modules.

Ansible Inventory and pytest-multihost output modules

---

src/aiohabit/actions/list.py
src/aiohabit/actions/ssh.py
src/aiohabit/errors.py
src/aiohabit/host.py
src/aiohabit/outputs/ansible_inventory.py
src/aiohabit/outputs/pytest_multihost.py
src/aiohabit/outputs/utils.py
src/aiohabit/run.py
src/aiohabit/utils.py

This is a follow up after(based on) https://github.com/pvoborni/aiohabit/pull/7 
To quickly show content of DB in human readable form
To make it very easy to SSH into a host based on value in various  configuration objects.
It is usually very time-consuming to "cat" e.g. inventory, copy the real hostname/IP, write all the SSH options including determining if it should use SSH key and what is its location.
The interactive mode even saves time with writing the fake hostname.
The bad UX of these actions is a need to provide metadata/config paths. In some other PR, we should figure out some reasonable default so that ppl can simply execute: `aiohabit list` and `aiohabit ssh`

Add "list" and  "ssh" actions

---

src/aiohabit/outputs/ansible_inventory.py
src/aiohabit/providers/static.py
src/aiohabit/run.py
src/aiohabit/transformers/__init__.py
src/aiohabit/transformers/static.py

Static provider
Static provider serves for mixing already provisioned hosts (pets)
with dynamically provisioned hosts. Alternatively all hosts can
be static. This can be useful for generating the outputs and using
other features.
Almost all operations are fake given that the hosts exist and cannot
be deleted by static provider. The most important parts is to provide
a name and ip.
ansible-inventory: fix bug when python interpreter not defined for os
E.g. so that the default python interpreter will be used.

Static provider

---

src/aiohabit/providers/aws.py

Fixing a small issue, `STATUS_MAP` was defined but not used. 
Issue described at https://github.com/pvoborni/aiohabit/pull/8#issuecomment-663308754.

AWS host: Return the right status

---

src/mrack/__init__.py
src/mrack/actions/output.py
src/mrack/outputs/pytest_multihost.py

- Print message only
- Handle output action error
- Running `mrack output` with an empty database breaks `python-pytest-multihost` config file. (E.g: Not running `mrack up` before trying that.)

Handle output action error + Update logger format

---

azure-pipelines.yml
pytest.ini

Set defaults for pytest and remove xunit1 format warning message
So that we can more easily inspect in azure if new tests were run  properly and also be able to see the results.
Mainly it removes warning message about deprecating xunit1 format.

Set defaults for pytest and remove xunit1 format warning message

---

src/mrack/providers/aws.py
src/mrack/transformers/aws.py

Using private addresses will result into unreachable host
without vpn tunnel or mechanism to access AWS network.
Add security group, tags, keypair to init of AWS provider.
They have to be defined in provisioning config.
Remove asserts and replace them with ProvisioningErrors

Use public AWS addresses instead of private ones and add some minor fixes to aws

---

src/mrack/providers/beaker.py
src/mrack/transformers/beaker.py

Add username='root' to fix ansible user
Added username='root' to beaker host object initialization
so inventory is created using ansible_user: root.
This is required because we are uploading public key
while provisioning to the root user and not user set
in the provisioning config.
The mismatched user causes unreachable host
when using generated ansible inventory.
Fix initialization of provider in a way
that we do not pass provisioning config
but only needed values.
Add status Queued as provisioning.

Add username='root' to fix ansible user

---

Makefile

Before:
```
$ make format
isort src
WARNING: Unable to parse file src due to [Errno 21] Is a directory: '/home/pvoborni/dev/freeipa/mrack/src'
isort tests
WARNING: Unable to parse file tests due to [Errno 21] Is a directory: '/home/pvoborni/dev/freeipa/mrack/tests'
black src
...
```
After:
```
$ make format
isort --recursive src
isort --recursive tests
black src
...
```

Remove false warnings produced by isort in make format

---

src/mrack/outputs/ansible_inventory.py
tests/unit/mock_data.py
tests/unit/test_ansible_inventory.py

The Ansible inventory output was not correctly adding hosts into groups. E.g.
group was not added when it was not defined in layout. Nested group was not
correctly found and host added.
This part is completely reworked and changes the behavior to:
- add only a host name reference (no vars) into custom groups
- add missing groups as children of 'all' group
- works with both "groups" and "group" defined in metadata
- add all hosts to 'all' with also variables. This ensures that the full host
object is defined only once.
Doc: https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html

ansible-inventory: rework generation of groups

---

src/mrack/providers/aws.py
src/mrack/providers/beaker.py
src/mrack/providers/openstack.py
src/mrack/providers/provider.py
test-requirements.txt

Methods provision_hosts, delete_hosts and to_host
were moved to provider.py as they can be easily
shared among the providers.
Added missing methods to provider.py to share
same structure. Not implemented methods will throw
a NotImplementedError() and they are ment to be
implmented per provider.
Moved host count to initialization of openstack
provider to set poll sleeps based on this.
For all providers moved STATUS_MAP to class
so from now on it is a class attribute.
Openstack's wait_till_provisioned now uses
instance and not only id to match inherited method.
Added optional username parameter to to_host method.

Refactor providers to share same code

---

docs/conf.py

From sphinx doc:
```
master_doc
The document name of the “master” document, that is, the document
that contains the root toctree directive. Default is 'index'.
Changed in version 2.0: The default is changed to 'index' from 'contents'.
```
Read the docs is using version < 2.0 thus it tries to find 'content's
and it fails.
Also changing theme to default - no real reason, thinking it will be
better.
Currently build fails with: 
`master file /home/docs/checkouts/readthedocs.org/user_builds/mrack/checkouts/latest/docs/contents.rst not found`

docs: set master doc to index

---

src/mrack/providers/aws.py
src/mrack/providers/beaker.py
src/mrack/providers/openstack.py
src/mrack/transformers/aws.py
src/mrack/transformers/beaker.py
src/mrack/transformers/openstack.py

Added basic image validation to AWS and Beaker provider
When os was not known in provisioning config, null/None
was taken and set as required image even for Openstack.
Value of 'os' is passed to req when image is not in place.
Then the 'os' value is seen in ValidationError messages
even instead of None/null in Openstack, AWS and Beaker.
Support image/distro definition from metadata.
And flag it with meta_distro/meta_image when used.
For AWS check image availability with boto.
When image is not present raise ValidationError

Add basic image validation to AWS and Beaker

---

src/mrack/host.py
src/mrack/providers/aws.py
src/mrack/providers/beaker.py
src/mrack/providers/openstack.py
src/mrack/providers/provider.py

Remove missing and unused print_basic_info method
Add loger info message to error parsing method.
Move the parse_errors to provider.py file.
Add property error to Host object.
Delete host now needs only host_id.

Remove missing and unused print_basic_info method

---

src/mrack/host.py
src/mrack/outputs/ansible_inventory.py
src/mrack/providers/aws.py
src/mrack/providers/beaker.py
src/mrack/transformers/aws.py
src/mrack/transformers/beaker.py
src/mrack/transformers/openstack.py

Support restraint_id defined in metadata and later
defined in inventory for the restraint jobs.
For this we pass requirements all the way
for later inventory generation.
Before:
```yaml
#metadata 
domains:
- hosts:
- group: ipaserver
name: f32.mrack.test
os: fedora-32
role: master
name: mrack.test
#mrack inventory
all:
children:
ipaserver:
hosts:
f32.mrack.test: {}
hosts:
f32.mrack.test:
ansible_host: ec2.compute.amazonaws.com
ansible_python_interpreter: /usr/bin/python3
ansible_user: fedora
meta_dc_record: DC=mrack,DC=test
meta_domain: mrack.test
meta_fqdn: f32.mrack.test
meta_ip: 10.10.10.10
meta_os: fedora-32
meta_provider_id: i-0d92949afagag
meta_role: master
```
After:
```yaml
#metadata 
domains:
- hosts:
- group: ipaserver
name: f32.mrack.test
os: fedora-32
role: master …
```

Support restraint_id record in metadata and fix destroy action

---

requirements.txt
test-requirements.txt

It is always better to require specific versions
of dependencies because pip always installs
the latest and they may break funcionality
or create conflicts when mrack is a dependency.

Require specific versions for mrack

---

src/mrack/transformers/openstack.py

Provisioning failed because requirements contained unexpected information.
I.e., the provider should receive only the information it expects or
are valid for OpenStack provisioning.
Removing the culprit lines: meta_image and restraint_id params.

Fix regression in up action with OpenStack provider

---

src/mrack/transformers/aws.py
src/mrack/transformers/beaker.py

These values are loaded from metadata when generating
inventory so they do not need to be passed to provider.

Remove unused values in aws and beaker transformation

---

src/mrack/providers/openstack.py

Trying to make the provider more stable if OpenStack is slow, e.g. under load.
It's not very clever method. But might work.

Increase OpenStack timeout to 6mins

---

src/mrack/providers/openstack.py
src/mrack/run.py

Fix OpenStack provisioning status translation
It is not needed to use a STATUS_MAP for translation status in
prov_result_to_host_data as it is done also in to_host of parent
class. Double translation doesn't work and thus everything provisioned
had incorrecly status : "other".
This has then a negative effect on ssh actione where no host is reported
as active.
Do not show traceback on ApplicationError
So that, e.g., on ssh action, when there are no active host, user
will not get an exception ending with:
```
raise ApplicationError("No active host available.")
```
But only:
```
No active host available.
```
Which is more user friendly.

Fix ssh action and improve its error UX

---

src/mrack/outputs/pytest_multihost.py

We have actually not used it at it cannot be assumed that
the user used for provisioning should be used for pytest-multihost.
E.g. a lot of tests rely on root - to be able to completely control
the remote machine. That cannot be done, e.g. with default cloud-user.
(Though it can often sudo to root)
Let's keep there the more simple configuration, where user is the
same for all host and is defined in provisioning config 'mhcfg' dir.

Do not set username for pytest multihost config

---

src/mrack/outputs/ansible_inventory.py

Support netbios in windows host definition for the inventory
```
$ cat metadata-fedora-win.yaml
domains:
- hosts:
- group: ipaserver
name: f32.mrack.test
os: fedora-32
role: master
name: mrack.test
- hosts:
- group: ad_root
name: root-dc.ad.test
os: win-2016
role: ad
netbios: ADTEST # <<< NEW SUPPORT
name: ad.test
type: AD
$ cat mrack-inventory.yaml
all:
children:
ad_root:
hosts:
root-dc.ad.test: {}
ipaserver:
hosts:
r82.mrack.test: {}
hosts:
r82.mrack.test:
ansible_host: 10.0.153.118
ansible_python_interpreter: /usr/libexec/platform-python
ansible_ssh_private_key_file: config/id_rsa
ansible_user: cloud-user
meta_dc_record: DC=mrack,DC=test
meta_domain: mrack.test
meta_fqdn: r82.mrack.test
meta_ip: 10.0.153.118
meta_os: fedora-32
meta_provider_id: 3b7672fb-006c-4efc-b085-d1f8128cd99f …
```

Support netbios in windows host definition for the inventory

---

.gitignore
setup.py
src/mrack/config.py
src/mrack/data/mrack.conf
src/mrack/data/provisioning-config.yaml
src/mrack/providers/beaker.py
src/mrack/providers/openstack.py
src/mrack/run.py

base on PR: https://github.com/neoave/mrack/pull/36
This commit implements a MrackConfig which allows to define options
and arguments otherwise needed in a configuration file and thus
save people's time with writing them in CLI.
Config file looks like:
```
[mrack]
mrackdb = config/mrackdb.yaml
provisioning-config = config/provisioning-config.yaml
metadata = config/metadata.yaml
```
Where each value is optional and existance of the config is also
optional.
Mrack looks for the config on these locations:
- user provided path via -c or --mrack-config global option
- ./mrack.conf
- ~/.mrack/mrack.conf
- /etc/mrack/mrack.conf
It also changes CLI of commands:
- metadata is no longer an argument but an option: -m or --metadata
- provisioning config shortcut changes to global -p
With these changes …

MrackConfig: improve the approach to be object based and easy to extend 

---

src/mrack/transformers/aws.py
src/mrack/transformers/beaker.py
src/mrack/transformers/openstack.py
src/mrack/transformers/transformer.py

Move common methods to transfromer.py
to have less copy pasted code.
Added more debug messages to transformation procedure.

Move common methods to transfromer.py and add more debug messages to transformation procedure.

---

.github/workflows/check-commits.yml

Checks the future commit headers to be compatible with
the project python-semantic-release.

chore: Add check-commits action for commits

---

src/mrack/outputs/ansible_inventory.py

When inventory was created the expected key value
for the parent_domain in host section should be
meta_parent_domain playbook will not fail with:
The error was: 'meta_parent_domain' is undefined

fix: Use meta_ prefix for parent domain

---

pyproject.toml
pytest.ini
src/mrack/actions/etchosts.py
src/mrack/run.py
tests/unit/data/etc/etc.hosts
tests/unit/data/etc/hosts_missing_end
tests/unit/data/etc/hosts_missing_start
tests/unit/data/etc/hosts_multi_end
tests/unit/data/etc/hosts_multi_start
tests/unit/data/etc/hosts_order
tests/unit/test_etchosts.py
tests/unit/utils.py

This is useful for cases where the fake hostname needs to be used
e.g. when accessing FreeIPA Web UI which is sensitive on used hostname.
It is uncomfortable task to read the values from `mrack list` and add
them manualy to /etc/hosts.
The change introduces two commands to help with this case:
* `$ mrack eh add` to add all active hosts into /etc/hosts
* `$ mrack eh clear` to remove all records added by mrack.
Mrack adds two markers into the /etc/hosts file and adds records
between them. This should work also with multiple runs of mrack in
separate tests. If the section already contains the fake hostname then
this line is overwritten with a new value. This is useful when
provisioning hosts for the same task after they were previously
removed.
Signed-off-by: Petr Vobornik …

Simple way to add hosts into /etc/hosts file

---

src/mrack/actions/output.py
src/mrack/config.py
src/mrack/data/mrack.conf
src/mrack/outputs/ansible_inventory.py
src/mrack/outputs/pytest_multihost.py
src/mrack/run.py
tests/integration/test_actions.py

Adding a possibility to change Ansible inventory and pytest multihost
configuration output file paths in a mrack config file. So that user
can use directly a custom location.
Example of such config:
```ini
[mrack]
mrackdb = config/mrackdb.json
provisioning-config = config/provisioning-config.yaml
metadata = config/metadata.yaml
ansible-inventory = config/test.inventory.yaml
pytest-multihost = config/pytest-multihost-config.yaml
```

feat: Output file paths configurable in mrack config

---

.github/workflows/pre-commit.yml
.github/workflows/test-and-release.yml
README.md
pyproject.toml
setup.py
src/mrack/__init__.py

Added release workflow to be run by hand:
This workflow depends on test and pre-commit runs:
And after these succeeds runs the python-semantic-release action:
In this action:
- a new commit with changed version and changelog is pushed to master
- a new tag is added to the commit above with particular release version
- a new mrack package is being release to PyPi (prerequisite: secret with PYPI_TOKEN - already set)
Please note: the release 0.3.1 will not be created becaue it has been already this is why test action is failing here: https://github.com/Tiboris/mrack/runs/1448905490?check_suite_focus=true (see: https://pypi.org/help/#file-name-reuse)

chore: Add release workflow to github actions

---

src/mrack/providers/provider.py

When rebasing the Podman provider I've noticed this bug. It was failing for Podman as it has no STATUS_MAP but the line is IMHO incorrect for all others. It may be hard to notice as it defaults to STATUS_OTHER. I did not test if it works though.
Description:
parse_errors works with Host objects which already have the normalized status so usage of STATUS_MAP is incorrect.

fix: Remove double status translation in parse_errors

---

src/mrack/outputs/ansible_inventory.py
src/mrack/outputs/pytest_multihost.py

The logic was not working as the comment said. The cause was that
`mhcfg` already contained the value from provisioning config. So
we need to check the metadata to detect the situation.

fix: Fix making ssh_key_filename absolute for default behavior.

---

src/mrack/outputs/pytest_multihost.py

If host IP was not resolvable into DNS record, external_hostname was
null and thus pytest-multihost could not connect to the host.
This resolves the issue with using IP as a backup.

fix: pytest-multihost: handle unresolvable IP into DNS

---

src/mrack/providers/aws.py
src/mrack/providers/beaker.py
src/mrack/providers/openstack.py
src/mrack/providers/provider.py
src/mrack/providers/static.py

Optional (currently applied only for OpenStack) provisioning strategy
to retry provisioning of host which ended with error in a provisioning
attempt.
This is useful if environment gets into state where the provisioning
is a bit unstable but in general working. I.e. succeeds for some host
and fails for others.
The Retry strategy:
1. tries to provision all hosts
2. if some failed, delete them and retry only for these hosts
3. if they fail more than max_attempts time(default: 5), fail the job
Default strategy:
- do 1.
- if some failed, fail the job
In each job failure case:
- delete all hosts

feat: Retry provisioning strategy

---

src/mrack/providers/aws.py
src/mrack/providers/beaker.py
src/mrack/providers/openstack.py
src/mrack/providers/provider.py

When openstack image was not in provisioning config
it was not loaded to known images.
Now we try to load missing images and store to provider's
known images if they were specified in metadata but not
in provisioning-config.yaml

fix: load possible missing image specified in metadata

---

src/mrack/providers/beaker.py
src/mrack/utils.py
tests/unit/utils.py

When `~` is used in path for mrack.conf the later
operation open('`~/.mrack/mrackdb.json`', 'w') fails with an
exception FileNotFoundError:
[Errno 2] No such file or directory: '~/.mrack/mrackdb.json'

fix: mrack.conf '~' causes no such file or directory

---

src/mrack/providers/aws.py
src/mrack/providers/openstack.py

There was an issue when reading image.name for image
for which user did not have proper read rights and
is not authorised to use it - Nonetype has no attribute name
refactor overcomplicated code in openstack in second commit

fix: AWS Error for non authorized user reading image + refactor overcomplicated join

---

requirements.txt
test-requirements.txt

While still a good practice to pin the versions of dependencies we found some issues with conflicting dependencies.
This change tries to install greater than or equal to latest major version (or minor if versio is 0.X).
It keeps the exact version (`==`) for boto3 and botocore because of a known conflict in the production environment.

chore: change pinned version from strict to range

---

src/mrack/run.py

Turns:
```
$ mrack eh add
/usr/lib/python3.9/site-packages/click/core.py:1256: RuntimeWarning: coroutine 'eh' was never awaited
Command.invoke(self, ctx)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Adding hosts to /etc/hosts file
Done
```
Into:
```
$ mrack eh add
Adding hosts to /etc/hosts file
Done
```

fix: mrack eh add no longer complains about coroutine 'eh' not awaited

---

README.md

Fix missing param in README.md file `--metadata`

refactor: Fix missing param in README.md file

---

src/mrack/actions/ssh.py
src/mrack/outputs/ansible_inventory.py
src/mrack/providers/podman.py
src/mrack/providers/utils/podman.py
src/mrack/run.py
src/mrack/transformers/__init__.py
src/mrack/transformers/podman.py

Add basic support for Podman.
So far supported:
rootless containers
Ansible via using "podman" connection in Inventory
ssh action via attaching to the container
TODO:
attach network the the containers
privileged containers
custom user mapping for provider as containers have different user than cloud images
I.e. test bench will be to install a FreeIPA server with couple replicas.
Commands usable for testing:
mrack -c $SOME_PATH/provisioning-config.yaml up -p podman $OTHER_PATH/simple_hosts.yaml 
mrack -c $SOME_PATH/provisioning-config.yaml destroy $OTHER_PATH/simple_hosts.yaml
mrack -c $SOME_PATH/provisioning-config.yaml ssh $OTHER_PATH/simple_hosts.yaml
mrack -c $SOME_PATH/provisioning-config.yaml list $OTHER_PATH/simple_hosts.yaml
ansible  -i mrack-inventory.yaml all  -m shell -a "cat …

feat: basic part of podman provider

---

src/mrack/providers/openstack.py
src/mrack/transformers/openstack.py

fix: more verbose print about available networks
So that we can see more details in debugging.
fix: Handle ServerError in OpenStack provisioning
If OpenStack server returns e.g. error 503, provider code doesn't handle it well and whole Mrack fails. This should catch it with    certain error tolerance/retry - e.g. if it was a fluke.

fix: Handle ServerError in OpenStack provisioning

---

src/mrack/providers/provider.py

To fix:
```
Retrying to provision these hosts.
Max attempts(5) reached. Aborting.
$somepath/mrack/providers/provider.py:137: RuntimeWarning: coroutine 'Provider.abort_and_delete' was never awaited
self.abort_and_delete(hosts_to_delete, error_hosts)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

fix: provider: await abort_and_delete

---

src/mrack/errors.py
src/mrack/providers/openstack.py

If OpenStack RC file is not loaded, openstack provider failed with
unhandled TypeError exception which is thrown by asyncopenstackclient
AuthPassword.
This fix catches the exception and writes friendly error message.

fix: OpenStack provider does not crash if no credentials are provided

---

src/mrack/providers/beaker.py
src/mrack/providers/openstack.py

Increase polling times so that Mrack doesn't poll very often to not overload the server when a lot of hosts is provisioned.
Current setting should be approx:
```
hosts   init_wait   poll_time   After 10mins    After 15mins
1       15.65        7.22          48.77           69.55
3       16.95        7.66          46.82           66.41
7       19.55        8.54          43.67           61.23
10       21.50        9.20          41.81           58.11
30       34.50       13.60          35.66           46.69
100       80.00       29.00          39.34           44.52
200      145.00       51.00          56.88           59.82
```
Where "After 10/15mins" is poll_time after the time, but it is not a precise value (did not want to spend time on calculating it).

feat: OpenStack: increase polling time based on number of hosts

---

requirements.txt

Python 3.9 has removed the deprecated method 'encodestring' from base64 module.
It needs to be replaced by 'encodebytes'.
Beaker version 28.1 has the fix in place so require at least this
version.

fix: Require beaker version with support for python 3.9

---

src/mrack/outputs/ansible_inventory.py
src/mrack/providers/podman.py

Fixing ansible inventory generation for podman because db_host has no
attribute id.
Fixing AttributeError: 'PodmanProvider' object has no attribute 'strategy'.
Adding status map to podman

fix: podman ansible inventory and status_map for podman

---

requirements.txt

Replace exact versions of boto3 and boto-core with "greater than" and setting an older version because it's the latest available for Fedora 32.
It will install latest via pypi, pinned version is not a requirement anymore because production conflicts with linchpin are not a problem anymore.

chore: change boto's minimum version required

---

.gitignore
mrack.spec
pyproject.toml

Versioning automated via Github Actions.
Dependencies have no pinned version.

feat: Add RPM spec file

---

src/mrack/providers/openstack.py

Handling all nova client calls as done in 46048c01f6ae3224e9d49e711e610b28497f63df.
Also, if mrack fails to provision some hosts it must not return 0, an Ansible playbook might misinterpret that as a success.

fix: Handle provision errors

---

.github/workflows/check-commits.yml
.github/workflows/pre-commit.yml
.github/workflows/test-and-release.yml
pyproject.toml

Test & Release action now updates also specfile
using GH secrets with corresponding actor name
and e-mail address to be used in spec's changelog.
Update action names to be more human friendly
Use latest python-semantic-release version.

chore: Update release action to update specfile changelog

---

setup.py

Fix URL used by Python Package Index.
---
**Note:** A webhook is configured to notify COPR when a release is published.
We can use this commit to test that.

chore: Update project homepage

---

.github/workflows/test-and-release.yml

Add action step to trigger COPR after a new release is created.
Using Github's built-in webhooks failed to talk to COPR "after release", so this should be more reliable.
--- 
**TO DO:**

chore: Trigger COPR to build rpm

---

.pre-commit-config.yaml
src/mrack/actions/ssh.py
src/mrack/actions/up.py
src/mrack/providers/provider.py
src/mrack/run.py
src/mrack/utils.py

After a host in provisioned we do check ssh connectivity
to the host itself and claim it is ready only after ssh
connection is successful. If ssh connection fails we
mark this host as an error host delete it and try to
go with reprovision strategy.

feat: use ssh to check VM availability after provisioning

---

src/mrack/data/provisioning-config.yaml
src/mrack/transformers/openstack.py

By default Nova's metadata informatation if retrieved via HTTP, setting `enable_config_drive` to True in provisioning-config will make metadata available via a config drive, a special drive that are attached to an instance when it boots.
This is helpful when connection is not stable during host booting stage, host would be unreachable because cloud-init is failing to injecting SSH keys into it.
This reduces the chance of hosts being provisioned but not accessible.
---
Raw data on `.mrack.db` shown that setting as "" (empty string). This behavior continues if `enable_config_drive` is False or not set.
From `/var/log/cloud-init.log` with Config Drive **disabled**:
```
2021-04-19 17:59:19,445 - dhcp.py[DEBUG]: Received dhcp lease on eth0 for ************/255.255.252.0
2021-04-19 17:59:19,445 …
```

feat: Enable config drive in OpenStack

---

src/mrack/actions/ssh.py
src/mrack/data/provisioning-config.yaml
src/mrack/data/seccomp.json
src/mrack/outputs/ansible_inventory.py
src/mrack/providers/beaker.py
src/mrack/providers/podman.py
src/mrack/providers/provider.py
src/mrack/providers/utils/podman.py
src/mrack/transformers/beaker.py
src/mrack/transformers/podman.py

mrack now support advanced podman provisioning
to enable custom way of running pods with podman
we should add podman section to provisioning config
something like:
```
podman:
images:
fedora-32: tdudlak/snappeas:fedora-32
fedora-33: tdudlak/snappeas:fedora-33
fedora-rawhide: tdudlak/snappeas:fedora-rawhide
pubkey: config/id_rsa.pub
default_network: mrack-network
podman_options:
"--tmpfs":
- "/tmp"
"-v":
- "/sys/fs/cgroup:/sys/fs/cgroup:ro"
"--network": "enable_ipv6=true"
```
Use ssh to connect to container provisioned by mrack
instead of ansible connection to prevent some issues
with connection and built in ansible modules so
the container acts like a vm.
NETWORK: Podman now use network name created by composing
default network from provisioning config and domain name.
PODS: name of the …

feat: Advanced podman support and several minor updates and bugfixes

---

src/mrack/host.py
src/mrack/providers/provider.py
src/mrack/utils.py

Aims to resolve https://github.com/neoave/mrack/issues/98
After this patch:
```
2021-04-19 12:56:24,432 mrack.utils INFO ssh -o 'StrictHostKeyChecking=no' -o 'UserKnownHostsFile=/dev/null' -l fedora -i config/id_rsa 10.0.99.34 echo mrack
2021-04-19 12:56:24,456 mrack.providers.provider INFO OpenStack: 1 hosts were not provisioned properly, deleting.
2021-04-19 12:56:24,457 mrack.providers.provider ERROR OpenStack: Error: Could not establish ssh connection to host d0160fba-803e-4ed8-bab4-4b42c248849d with IP 10.0.99.34
```

fix: missing error logging while checking the ssh connection

---

src/mrack/actions/ssh.py

utils.ssh_to_host requires to have global_context initialized but
with introduction of it ssh action was not ammended. Without it
mrack crashed on sshing to a host.
This fix is initializing utils.global_context in ssh_action and
thus fixing the issue.

fix: ssh action crashes as it misses global_context

---

src/mrack/providers/provider.py
src/mrack/utils.py

feat: check ssh connectivity outside of pares_error_hosts more than once
Move the ssh connectivity check outside of the
pares_error_hosts method to distinguish the functionality
and to be able to gather asynchronous results later.
Retry the ssh connection after if fails to not destroy
slower systems which may not have set up the proper
ssh key into allowed keys.

feat: check ssh connectivity outside of pares_error_hosts more than once

---

mrack.spec
src/mrack/providers/podman.py
src/mrack/providers/utils/podman.py

Pull podman image in provisioning preparation
to not block the provisioning or pull one image
more than once which may cause unexpected errors.
Create podman networks in provisioning preparation
to not block the provisioning or ty to create already
created networks which may cause unexpected errors.

feat: Pull podman images and create networks in preparation

---

pyproject.toml
setup.py
src/mrack/__init__.py
src/mrack/run.py
src/mrack/version.py

From my PoV, this is cleaner as there is version only on one location in the mrack package and it can be even more easily imported anywhere else. 
The second commit is also logging the version into mrack.log so that it is usable in debugging.
Alternative to: https://github.com/neoave/mrack/pull/109

feat: Add --version option to mrack cli - alternative implementation

---

src/mrack/providers/openstack.py
src/mrack/providers/provider.py
src/mrack/transformers/openstack.py

Moving network translation to provider will help us 
to find new network for openstack VM when there
is a problem with network pools (insufficient ips)
that will help to choose another pool within openstack.
Transformer now only informs about network type
provider picks the network at every provision retry.

feat: move network translation to provider and remove redundant validation

---

src/mrack/providers/aws.py
src/mrack/providers/openstack.py
src/mrack/providers/podman.py
src/mrack/providers/provider.py

feat: Wait for provider resources up to hour
Checking resources more than once should help
to provide better results when we are facing
the providers to be overocupied.
feat(OpenStack): Check openstack response for resources issue
OpenStack may be oversubscribed so even when we do not reach
our quota limit provisioning may fail due to lack of resources.
In such scenario (OpenStack run out of hosts to provision)
we check the response from server and act based on the fact
that OpenStack itself is being fully loaded and does not have
free resources to provide for our server.
docs: Update method docsting as it does not Validate hosts anymore
feat: gracefully destroy servers after traceback
This allows us to create dummy Host object based
on the ProvisioningError traceback arguments
where we …

feat: Check and wait for resources when provisiong

---

.github/workflows/test-and-release.yml

Our release automation is failing due to missing libraries

chore: Add libvirt-dev distro dep to GH action

---

src/mrack/transformers/beaker.py

Only BaseOS variant is available for RHEL9.0 in Beaker.

fix: use BaseOS as variant for RHEL9.0 in Beaker

---

src/mrack/providers/beaker.py

Add feature which enables adding distro tags specified
in the provisioning config in beaker section like:
```
beaker:
distro_tags:
FEDORA-34%:
- NIGHTLY-TESTED
```
This allows us to specify distros with custom tags.

feat(Beaker): Add distro tag from provisioning conf

---

docs/guides/credentials.rst
docs/guides/strategy.rst
src/mrack/data/provisioning-config.yaml
src/mrack/providers/aws.py
src/mrack/providers/beaker.py
src/mrack/providers/openstack.py
src/mrack/providers/podman.py
src/mrack/providers/provider.py
src/mrack/providers/static.py
src/mrack/providers/virt.py
src/mrack/transformers/aws.py
src/mrack/transformers/beaker.py
src/mrack/transformers/openstack.py
src/mrack/transformers/podman.py
src/mrack/transformers/static.py
src/mrack/transformers/transformer.py
src/mrack/transformers/virt.py

feat(Beaker): use timeout instead of number of retries
using number of retries is being replaced by timeout
to help users to redefine easily using provisioning config
timeout variable should be more user friendly
feat: add possibility to change strategy per provider in provisioning config
change default openstack behavior to abort
refactor(Beaker): Use hub url in messages
refactor(Beaker): fix the typo in message
refactor(static): remove method which is inherited

feat:  Update providers to have configurable strategy and minor fixes

---

src/mrack/actions/up.py
src/mrack/providers/beaker.py
src/mrack/providers/podman.py
src/mrack/providers/provider.py
src/mrack/providers/virt.py

fix(Virt): Add de-sync state and fix error parsing.
fix: destroy active VMs after other providers fail
Fixing the use case with multi provider failed run.
In case of at least 2 providers in metadata and one
failing, successfully provisioned hosts were not
destroyed as part of freeing resources.
e.g.:
if:
- Beaker fails
- Openstack succeeds
then
- Beaker cancel jobs
- Openstack resources keeps hanging not destroyed.
Adding block of code to raise an exception when
other than ProvisioningError occurred.
Resolves: https://github.com/neoave/mrack/issues/129

fix: destroy active VMs after other providers fail

---

src/mrack/providers/provider.py

number of attempts should be greater than max_retry
and not greater or equal than max_retry because
other way first attempt to provision will be
considered as first retry and provisioning will end
after reaching count 1 without reprovisioning retry
this was causing retry strategy to abort after
1st attempt even when max_retry was set to 1.

fix: attempts should be greater than max_retry

---

README.md
docs/guides/mrack_lib.rst
src/mrack/actions/action.py
src/mrack/actions/destroy.py
src/mrack/actions/etchosts.py
src/mrack/actions/list.py
src/mrack/actions/output.py
src/mrack/actions/ssh.py
src/mrack/actions/up.py
src/mrack/context.py
src/mrack/providers/beaker.py
src/mrack/providers/provider.py
src/mrack/run.py
src/mrack/utils.py
tests/integration/test_actions.py

Use GlobalContext class in runtime
which allows us to use mrack with only this context
and as a library with only creating desired actions
Up/Destroy/... and calling them in python scripts.
some minor fixes are also included in this PR

feat: Use GlobalContext class

---

src/mrack/providers/beaker.py
src/mrack/transformers/beaker.py
src/mrack/utils.py

mrack now supports the hostRequires in the host metadata
or default in provisioning config yaml.
The hostRequires for the host should look like following:
```yaml
hostRequires:
or:
- hostname:
_value: foo1.bar.baz.com
_op: "="
- hostname:
_value: foo2.bar.baz.com
_op: "="
and:
- system:
memory:
_value: 8000
_op: ">"
- arch:
_value: x86_64
_op: "="
- system_type:
_value: Machine
_op: "="
- key_value:
_key: HVM
_value: 1
_op: "="
- disk:
size:
_value: 137438953472
_op: ">"
```
Which will result into following xml for the job specification:
```xml
<hostRequires>
<or>
<hostname value="foo1.bar.baz.com" op="="/>
<hostname value="foo2.bar.baz.com" op="="/>
</or>
<and>
<system>
<memory value="8000" op="&gt;"/>
</system>
<arch value="x86_64" op="="/>
<system_type value="Machine" op="="/> …
```

feat(Beaker): Add parsing of hostRequires to the job

---

src/mrack/outputs/ansible_inventory.py
src/mrack/providers/aws.py
src/mrack/providers/beaker.py
src/mrack/providers/openstack.py
src/mrack/providers/podman.py
src/mrack/providers/provider.py
src/mrack/providers/static.py
src/mrack/providers/virt.py
src/mrack/utils.py
tests/unit/test_utils.py

This is  an alternative implementation to https://github.com/neoave/mrack/pull/146 consisting of 3 changes. The actual fix, which is very small + 2 preparations where refactoring to pass the `req` is the biggest.
**fix(openstack): use shortnames for Windows vm names**
Windows machines get hostname often by Cloudbase-Init. But
windows host support setting only shortnames (domain is added
when the host joins AD domain). OpenStack derives the hostnane
from vm name (until nova version 2.90 where hostname attr is added).
Thus we set shortname to support this also on older OpenStacks.
**feat: add shortname in Ansible inventory output**
It is added in meta_hostname attribute as often shortnames are
referred as hostnames.
**refactor: pass req to to_host method**
Or in other words, do not loose …

feat: shortnames for windows machines in Openstack provider + shortname in Ansible inventory

---

src/mrack/outputs/pytest_multihost.py

mhcfg section from provisioning-config is default
and could be extended by user provided mhcfg section
from metadata, thus using this order for `|` operator

refactor: use builtin operator to merge dictionary

---

src/mrack/providers/openstack.py

In some cases when network has an outage or is temporarily
removed etc. mrack would raise an exception when getting
the "id" from network which is set to 'None' which is
obvious AttributeError: 'NoneType' object has no attribute 'get'

fix(OpenStack): Do not raise exception when using unavailable network

---

src/mrack/providers/provider.py
src/mrack/providers/virt.py

When image for Virt provider is not accessible we
happen to raise an exception:
TypeError: 'TestcloudImageError' object is not iterable
This should fix above exception and also tune behavior
when preparation of resources is failing.

fix(Virt): Handle traceback when image is not accessible

---

src/mrack/providers/aws.py
src/mrack/providers/beaker.py
src/mrack/providers/openstack.py
src/mrack/providers/static.py

Based on latest changes method prepare_provisioning
should return boolean value which means succes/fail
ref: a0de8475659153fd3fb39133a34f56729d0e561c

fix: prepare_provisioning now shall return bool value

---

src/mrack/actions/ssh.py
src/mrack/utils.py

SSH action was previously redirected to PIPEs and thus it stopped
working from a user perspective as nothing was visible.
This patch is bringing the original behavior back.
Regression was caused by commit: 19d513ba246ef4be02a0ce3d22fbb0faea971ce8

fix: SSH action - do not redirect to PIPEs

---

src/mrack/utils.py
tests/unit/conftest.py
tests/unit/test_config_search.py
tests/unit/test_utils.py

**feat: search also provider config for username**
Cloud images might have a different default user based on provider, e.g.
RHEL has ec2-user but OpenStack image has cloud-user. This allows to
define default user per OS in provider section of provisioning config.
**feat: find_value_in_config_hierarchy utility method**
For getting a configuration value from the most specific to the
least specific. Design in a way to be usable for multiple of attributes.
E.g. first looking in host object then host definition in metadata then
in provider configuration and then in global provisioning configuration.

feat: search also provider config for username

---

src/mrack/providers/aws.py
src/mrack/transformers/aws.py

Requires: https://github.com/neoave/mrack/pull/158
**feat(aws): support for PrivateIpAddress**
When instance is provisioned with VPC which does not have a public
IP address, mrack is not able to get IP and fails. So changing the
behavior to try also Private IP if Public is not present.
**feat(aws): subnet support**
Adding possibility to define subnet to use for the instances. This
is needed, e.g. when instance needs to use a non-default VPC.
**feat(aws): multiple security groups**
Add support to be able to use multiple security groups and thus be able
to fine tune the inbount and outbound commnucation rules.
Note: there might be a small regression in validation in multiple security groups patch, where there is a possibility for alternate definitions but one is required and the other not. …

feat: multiple aws enhancements (PrivateIPAddress, multiple security groups, Subnet)

---

src/mrack/transformers/aws.py
src/mrack/transformers/beaker.py
src/mrack/transformers/openstack.py
src/mrack/transformers/podman.py
src/mrack/transformers/transformer.py
src/mrack/transformers/virt.py

It may change some behavior a little but is mostly a refactoring.
This is unifying the logic to get image definitions across transformers.
WiIl use it as a base for a next patch in `aws` provider to get images by tag.

refactor: use hierarchy search for images and distros

---

src/mrack/providers/aws.py
src/mrack/transformers/aws.py

rebased on top of: https://github.com/neoave/mrack/pull/161
Add a new way to define an AWS EC2 image in a provisiong config in addition to ami ID.
The following is valid:
```
images:
fedora-34: ami-0d3c5199abb29a7ae
fedora-35: { tag: { name: compose, value: mrack-fedora-35-latest } }
```
This allows for a seperate tool to upload new image with the same purpose and mrack automatically picks the latest one with the given tag.
Currently only one tag is supported and it searches in all images.
Possible improvements:
- more tags
- limiting to private images

feat(aws): defining AMIs by tags

---

src/mrack/providers/aws.py
src/mrack/transformers/aws.py
src/mrack/utils.py
tests/unit/conftest.py
tests/unit/test_config_search.py

This is only 1 commit but rebased on top of https://github.com/neoave/mrack/pull/162 (which is on top of https://github.com/neoave/mrack/pull/161 )
Spot instances are a great way how to save money for CI purposes.
https://aws.amazon.com/ec2/spot
This is inital implementation where the only possible option is to
ask for spot instance, but not define SpotOptions - this can be
extended later if wanted.
How to use:
- set `spot: True` in `aws` provider to enable it globally
- set `spot: True` in host section in job metadata file to request
a spot instance for this particular host.
Additional changes:
- removes stopping instance on destroy as it doesn't work with
default behaviour of spot instances + correctly handle exception when
stopping fails (previous behaviour crashed mrack)
- prepares a …

feat(aws): request spot instances

---

src/mrack/providers/virt.py

testcloud is capable to inject password to linux
instances but not to windows one when provisioning
thus remove the password from the result when
the instance is identified as windows host.

fix(Virt): remove password when provisioning windows

---

src/mrack/outputs/ansible_inventory.py
src/mrack/outputs/pytest_multihost.py
src/mrack/outputs/utils.py
tests/unit/test_output_utils.py

Ansible inventory's `ansible_host` or pytest-multihost's `external_hostname` currently by default tries to resolve host's IP address and use the DNS name if resolution is successful.
This change allows to disable this behavior by setting:
`resolve_host: False`
Somewhere in the configuration hierarchy (metadata host, provider config, or global provisioning config).

feat: possibility to disable host DNS resolution in outputs

---

.pre-commit-config.yaml
test-requirements.txt

Recent release of Click makes current version of Black to break. This issue is solved in newest version of Black 22.3.0
See more about the issue in https://github.com/psf/black/issues/2964
Signed-off-by: David Pascual <davherna@redhat.com>

chore: Update Black pre-commit hook version to 22.3.0 to solve click dependency issue

---

src/mrack/host.py
src/mrack/outputs/ansible_inventory.py
src/mrack/providers/openstack.py
src/mrack/providers/provider.py
tests/unit/mock_data.py
tests/unit/test_ansible_inventory.py

In order to know what image is the "latest" tag pointing to in compose name in Openstack,
meta_compose_id and meta_compose_url fields from image meta information are
printed out in the log and added to ansible inventory output.
Implemented in a way that allows extension for other providers with extra custom fields in the future,
or images that don't have those fields at all.

feat: printout compose_id when using -latest image pointer for Openstack

---

pytest.ini
src/mrack/data/provisioning-config.yaml
src/mrack/transformers/beaker.py
tests/unit/mock_data.py
tests/unit/test_beaker_transformer.py

Before this patch the distro variant could not be configured
and was hardcoded in the source code of the mrack project.
With this patch we support the old way and also a new way
of specifying the distro variants in the provisioning-config.
Updated the example provisioning-config.yaml file with latest
beaker feature examples.

feat(Beaker): Support distro variant configuration

---

src/mrack/transformers/transformer.py

When OS image in metadata is not found in provisioning
config, there was a traceback causing mrack to fail.
Adding default value solves the problem and prints expected message.

fix: image transformer none value in requirements 

---

src/mrack/host.py
src/mrack/providers/aws.py
src/mrack/providers/beaker.py
src/mrack/providers/openstack.py
src/mrack/providers/podman.py
src/mrack/providers/provider.py
src/mrack/providers/static.py
src/mrack/providers/utils/podman.py
src/mrack/providers/virt.py
src/mrack/transformers/transformer.py

Adding a host name from metadata or host object
where it is possible to increase readability of
the log messages and better debugging with only
using the log content. Before this patch there
were logging messages that were describing the
error but from the log message we could not tell
which host was causing that.

style: Increase readability of logs by using host

---

src/mrack/transformers/transformer.py

when the image is not found in the provisioning
config mapping the _get_image() method defaults
to the host['os'] value from the input metadata

docs: Update the _get_image() method doc string

---

src/mrack/actions/up.py
src/mrack/providers/aws.py

Move tagging into creation request itself
When the creation of the instance is too slow
on the ec2 side we get a traceback that instance
does not exist (yet) and we need would need
to wait a bit in order to tag it.
Move tagging into request itself and do it at instance creation
adding some trivial patches:
- [refactor: remove collon from error string]
- [fix: return False when ValidationError is raised]

feat(AWS): Move tagging into creation request itself

---

src/mrack/outputs/ansible_inventory.py
src/mrack/outputs/pytest_multihost.py
tests/unit/mock_data.py
tests/unit/test_ansible_inventory.py
tests/unit/test_pytest_multihost.py

Make it possible to define arbitratry attributes prefix with meta_
in host section of job metadata file.
All of these attributes are then copied to host part in ansible
inventory output.
It can serve for creation of playbooks which consumes these attributes.
Addtional, but probably rare use case, is to override the meta_ attrs
which are derived from other others by mrack.

feat: copyign meta_ attributes from host to ansible inventory

---

.github/workflows/test-and-release.yml

chore: Use python-version 3.9 and bump python-semantic-release for the release workflow

---

src/mrack/data/provisioning-config.yaml
src/mrack/providers/beaker.py
src/mrack/transformers/beaker.py
tests/unit/mock_data.py
tests/unit/test_beaker_transformer.py

get the ks_meta from host configuration, global
provisioning config or default hardcoded in code.
The priority is following:
- host
- provisioning-config.yaml
- default (if nothing set)
https://beaker-project.org/docs/user-guide/customizing-installation.html#kickstart-metadata-ks-meta

feat(Beaker): Support custom configurable ks_meta values

---

src/mrack/providers/beaker.py
src/mrack/transformers/beaker.py
tests/unit/mock_data.py
tests/unit/test_beaker_transformer.py

Moving the translation of requirement to specs
to the beaker transformer and support more options. Now the beaker specific configurations
can be defined in provisioning config,
host's beaker section. If nothing is specified
sane defaults are configured.

feat(Beaker): support configurable jobxml specs 

---

src/mrack/providers/beaker.py
src/mrack/transformers/beaker.py
src/mrack/utils.py
tests/unit/conftest.py
tests/unit/test_config_search.py

**refactor(beaker): move distro_tags and hostRequires to transformer**
From provider as transformer is the component which should work with
provisioning config.
Also remove the mrack_beaker from specs as it is no longer needed.
**fix: issue when searching for value when dict_name == attr**
When searching for value using find_value_in_config_hierarchy the method
might return the entire dictionary with name according to dict_name when
the search attribute name is the same as dict_name and the dict doesn't have
a default value nor value according to provided key.

refactor(beaker): move distro_tags and hostRequires to transformer

---

README.md
mrack.spec

Splitting mrack to:
- mrack
- mrack-cli
- python3-mracklib
- python3-mrack-aws
- python3-mrack-beaker
- python3-mrack-openstack
- python3-mrack-podman
- python3-mrack-virt
where python3-mracklib contains only static provider and all the
scripts and provisioning base logic.
we can install mrack-{aws,beaker,openstack,podman,virt}
providers in addition to static provider extending
the functionality and create modular solution where only
needed providers can be installed.
Package mrack contains all supported providers.
Package mrack-cli contains mrack command.
We are using Suggests directives for OpenStack dependencies
so in fedora where these are not available build will pass.
Resolves: https://github.com/neoave/mrack/issues/113 
This MR depends on:

feat: Split mrack into multiple rpms

---

src/mrack/providers/beaker.py

fix(Beaker): traceback when hub is not accessible at session creation

---

.github/workflows/pre-commit.yml
.github/workflows/test-and-release.yml

Trying to fix this warning by usage of latest-greatest actions:
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/setup-python, pre-commit/action, actions/setup-python, actions/checkout

chore: bump versions of GitHub actions

---

src/mrack/actions/etchosts.py
src/mrack/providers/podman.py
src/mrack/transformers/beaker.py
src/mrack/utils.py
tests/unit/utils.py

pylint started to complain about unspecified encoding, thus adding to open functions.

fix: add the encoding to multipple open function calls 

---

tests/unit/test_beaker_transformer.py

test(Beaker): add check for additional keys
Add check for additional keys [tasks, redention_tag, product]
to beaker transformer tests.
Resolve: https://github.com/neoave/mrack/issues/186
refactor(Beaker): transformer test to use dictionary
Refactor beaker transformer test to use dictionary instead of multiple
parameters in function call. This increase readability of test.
Resolve: https://github.com/neoave/mrack/issues/186

test: extend beaker tests

---

mrack.spec
src/mrack/actions/ssh.py
tox.ini

fix(Podman): Fix action ssh import failing if podman provider not found
When podman provider is not installed as plugin
we should not import it in ssh.
Ignoring the import error will fix tracebacks.
chore: bump python version in tox.ini
In our automation we rely on python 3.9
setting tox.ini to same version
fix(mrack.spec): remove unecessary statement
the python_provide should be used
for python*- packages only thus removing.
fix(mrack.spec): cli package files and deps
Fixing the cli package dependency by adding
the Requires: python3-click and removing
unnecessary file run.py from lib package
and move it to cli package where it belongs

fix: mrack spec fix, tox update and import fix

---

Makefile

To make buiding of rpms easier - for adhoc testing/development and sort of work as a documentation how to do it as it is easily forgotten when not doing often.

chore: rpm and clean-rpms targets in Makefile

---

src/mrack/run.py
src/mrack/utils.py

Python 3.11.0 completely dropped support for the
asyncio.coroutine. As it was already deprecated
we should use the proper way of decorating the
click functions in the mrack run.py.

fix: Do not use deprecated asyncio.coroutine wrapper

---

mrack.spec

As it is adding all dependencies to all rpms and ignoring the individual nuaces between packages. I.e. without this, we cannot install python3-mracklib without the rest.

chore: disable automatic runtime deps discovery for rpm build

---

mrack.spec
setup.py
src/mrack/config.py
src/mrack/data/mrack.conf
src/mrack/providers/aws.py
src/mrack/transformers/aws.py
src/mrack/transformers/openstack.py
src/mrack/transformers/transformer.py
tests/integration/conftest.py
tests/integration/test_actions.py

Owner and lifetime info will be added into VM's metadata for Openstack/AWS providers. This info will give info who owns the VM and what is the lifetime of the VM which will be used for notifying owners and cleaning up the resources based on lifetime of the VMs.
If owner info not fetched, user notified with custom error message for follow up action to take up.
Signed-off-by: ksiddiqu <ksiddiqu@redhat.com>

feat(openstack-aws): Add owner/lifetime info in VM's metadata

---

.github/workflows/test-and-release.yml

When branch protection is enabled only real
user (not gh-actions as it is bot) can push
to the main branch when there is Pull Request
required and approvals for particular PR.
With exception added to the users which can bypass the protection rules we should be able to release
with personal GH token generated for the user.

chore: Use personal GH token to release mrack

---

src/mrack/transformers/aws.py
src/mrack/transformers/openstack.py
src/mrack/transformers/transformer.py

Limitin only for certain providers is needed as the owner doesn't matter for static (vm already present somewhere, could be owned by completely different person), podman, libvirst (vm running on current machine, no need for owners).
But it makes sense for any cloud like OpenStack, AWS, Beaker.
Enabled only for AWS, OpenStack as Beaker doesn't work with ownership yet.

fix: validate ownership and lifetime only for AWS and OpenStack

---

src/mrack/actions/up.py
src/mrack/errors.py
src/mrack/providers/openstack.py
src/mrack/run.py
tests/unit/test_openstack.py

This is bit cosmetic change, adding MrackError class which is parent of all errors so later we just catch the MrackError exceptions.

fix: raise Validation error when validation fails and use MrackError

---

.github/workflows/check-commits.yml
.github/workflows/test-and-release.yml

This will not force the actions user credentials
to be stored into git config which will later
result in using github_token of release actor.

chore: change the persist credentials to false and bump commit msg checker version

---

src/mrack/context.py

When initializing the global context these files
should be passed to the init as optional param
when path is specified in mrack cli tool.
Otherwise mrack should only load the data from
the mrack.conf file records and rely on paths
set there for db and provisioning-config.

fix: make db file and provisioning file optional

---

.packit.yaml

This commit is enabling packit service for the mrack
project. see: https://packit.dev/docs/configuration/
To start using Packit we did:
- set up integration on GitHub side and selected free plan
- got approved by mapping FAS identity (tdudlak) to the
service via: https://github.com/packit/notifications/issues/482
by linking neoave organization with FAS account
- configured the wanted features via this commit
This commit sets up packit jobs to:
- check build per pull request
- trigger copr build after a release
- create fedora PRs to mrack project with updates 
- rights for packit user for the repo should be added (fedora)
- create koji build per commit merged to fedora's mrack
- create bodhi updates per each successful koji build
This allows us to forget about backporting pathces
to …

chore: Add packit service configuration

---

.packit.yaml

This configuration options sets up the packit tag template for packit to know what tag format to expect when checking the release to properly set the variables for the archives.
Resolves: https://github.com/neoave/mrack/issues/220

chore(Packit): Add upstream_tag_template to .packit.yaml

---

pyproject.toml
src/mrack/config.py
src/mrack/utils.py
tests/unit/test_utils.py

When parsing boolean values from string using bool() builtin funtion string which is not empty returns True Writing a util function to convert such strings
to proper boolean values. NOTE: distutil implementation: from distutils.util import strtobool
will be deprecated and removed in future python releases thus implementing a funtion ourselves might be
future proof solution at this time.

fix: Owner requirement boolean parsing from string

---

.github/workflows/pre-commit.yml
.github/workflows/test-and-release.yml
.pre-commit-config.yaml
.pylintrc
azure-pipelines.yml
src/mrack/outputs/ansible_inventory.py
src/mrack/outputs/pytest_multihost.py
src/mrack/providers/__init__.py
src/mrack/transformers/__init__.py
src/mrack/transformers/transformer.py
src/mrack/utils.py

Using latest python will help us to identify
latest changes and regressions early in upstream PRs. Bumped repo versions in .pre-commit-config.yaml
to point to latest stable releases per available check.

chore: Use python 3.10 in GH actions

---

.packit.yaml
src/mrack/providers/aws.py

chore(Packit): enable epel-8 and epel-9 updates and tests
fix(AWS): refactor sources to be py3.6 compatible
When considering mrack to be part of
the tmt which is used even in epel8 and epel9
we might be limited to not use latest python
features which one of them is := opearator.

fix(AWS): refactor sources to be py3.6 compatible and add epels to packit

---

mrack.spec
src/mrack/transformers/transformer.py

fix: Add cache decorator for older python versions.
fix(mrack.spec): Missing dependency in c8s for beaker-client

fix: Add several c8s fixes for missing deps and decorators

---

.packit.yaml

Missing ci.fmf sync causes fedora message being not recognized 
in dowsntream and thus expected tests to be marked as failed
even when tests might be run and passing. 

chore(Packit): Add missing ci.fmf to synced files

---

.packit.yaml
.pre-commit-config.yaml

The smoke test is uninstalling all packages and then trying to install them again to check if dependencies work correctly.
The issue is that version of package created by packit on pull request could be lower from dnf PoV than the one available e.g. in EPEL thus the EPEL version is used istead of the one which we are testing.
Thus c8s test is failing as it is picking up a package which has incorrect dependencies.
This PR is recording the initially installed package version to use it again on reinstallation and thus avoid the issue.

test: fix installation of right package in smoke tests

---

src/mrack/outputs/ansible_inventory.py
src/mrack/outputs/pytest_multihost.py
tests/unit/test_ansible_inventory.py

feat(AnsibleInventory): Allow additional domain level ansible inventory values
Add support for domain level ansible_inventory records which
can be eventually overwritten by host defined values.
Added unit tests to test this feature.   
feat(AnsibleInventory): Allow additional global level values
Add support for global level ansible_inventory records
which can be eventually overwritten by domain and host defined values.
Minor fix of logig in pytest multihost code - adding deepcopy.
test(AnsibleInventory): global level output values override
Add test for the feature to support global level
ansible_inventory records which can be eventually
overwritten by domain and host defined values.

feat: Allow domain and global section records for ansible inventory 

---

src/mrack/config.py
src/mrack/providers/aws.py
src/mrack/providers/beaker.py
src/mrack/providers/openstack.py
src/mrack/providers/podman.py
src/mrack/providers/provider.py
src/mrack/providers/static.py
src/mrack/providers/virt.py

feat: Do not use same sleep for every mrack run
Adding logic to randomize the timeout to basically
set the waiting timeout to vary from 45-75 minutes randomly
and the poll time to 45-75 seconds accordingly
so if there are multiple parallel runs of mrack they wait
different amount time before poll and increase chance to get resources
quicker than other concurrent runs of mrack requests
Add cooldown after error host was found to wait before
another retry and resource check cycle for random time
between one poll sleep and 2* poll sleep (45-75 s is one poll)
Add utilization method template to decide whether to
destroy all machines or to keep them while re-provisioning
to free some resources when there is provided highly utilized.
feat(AWS): Add utilization check method
feat(OpenStack): Add …

feat: Do not use same sleep for every mrack run

---

src/mrack/config.py
src/mrack/providers/openstack.py
tests/unit/conf/mrack.conf
tests/unit/conf/mrack_force_spread.conf
tests/unit/conf/mrack_no_spread.conf
tests/unit/conf/provisioning-config.yaml
tests/unit/mock_networks.py
tests/unit/test_openstack.py

The network spreading feature has aimed to utilize networks usage however for some particular products it might be not optimal to have resources on different networks. This patch is adding options to mrack.conf which can disable the feature and also set the acceptable threshold of network utilization for OpenStack.
network-spread = no/allow/force

feat(OpenStack): Provide a way to disable network spreading

---

.github/workflows/test-and-release.yml

Python-semantic-release had problems fetching
the commit's sha from work directory. This
issue should be fixed in latest release of action.

chore: Bump python-semantic-release to latest

---

.github/workflows/test-and-release.yml
.packit.yaml
mrack.spec
tests/smoke/smoke-test.sh

chore: set packit to sync changelog as well
chore: sync fedora spec to upstream to maintain changelog history for fedora
chore: Generate proper changelog from commit history when releasing
When releasing the package mrack.spec was not enriched
by the history of changes compared to previous release
this is enhancing the workflow to have proper changelog

chore: update the changelog properly and sync files for packit

---

mrack.spec

this is a leftover from fedora packaging

chore: change back mrack dist release to 1

---

src/mrack/providers/beaker.py
src/mrack/providers/openstack.py
src/mrack/providers/provider.py

fix(OpenStack): Add exception parameter when validation fails
Adding second parameter to ValidationError exception gets rid of mrack exiting with exception.
fix(Beaker): rerurn common dictionary when validation fails
when Beaker distro/image is not recognized by beakerhub
mrack failed with exception as newer code expects
dictionary error object.
fix: Use get method when host error object is a dictionary
This makes sure to not throw an exception when host.error
is not a dictionary and we can not use .get() method

fix(OpenStack/Beaker): validation fails with exception when image/distro not found

---

src/mrack/providers/openstack.py

Resolves: https://github.com/neoave/mrack/issues/248

fix(OpenStack): await loading limits to not break provisioning

---

docs/conf.py
src/mrack/actions/output.py
src/mrack/config.py
src/mrack/outputs/ansible_inventory.py
src/mrack/outputs/pytest_mh.py
src/mrack/outputs/pytest_multihost.py
src/mrack/run.py
src/mrack/utils.py
tests/integration/data/metadata-hosts.yaml
tests/integration/test_actions.py
tests/unit/test_ansible_inventory.py
tests/unit/test_pytest_mh.py
tests/unit/test_pytest_multihost.py
tests/unit/test_utils.py

This adds new output for pytest-mh configuration file. Pytest-mh is
a complete rewrite of pytest-multihost with additional features that
is going to be used by SSSD. See: https://pytest-mh.readthedocs.io
This PR also adds `config` section to metadata file that currently can
contain:
* `outputs`: list of output files, defaults to `"anisble-inventory", "pytest-multihost`
* `ansible/layout`: to overwrite inventory_layout from provisioning-config

feat: Add pytest-mh output and "config" section to metadata

---

tox.ini

Running `make test` or `tox` failed on building docs as the tox config did not use the docsi/requirements.txt and thus the required dependency which was recently added was missing.
This path is changing the tox run to use the docs/requirements.txt and thus is fixing the issue.

chore: fix docs dependencies in tox run

---

src/mrack/actions/ssh.py
src/mrack/config.py
src/mrack/outputs/ansible_inventory.py
src/mrack/providers/provider.py
src/mrack/utils.py
tests/unit/mock_data.py
tests/unit/test_ansible_inventory.py
tests/unit/test_utils.py

This implements configurable ssh options according to design:
https://mrack.readthedocs.io/en/latest/designs/ssh_options.html
With the idea that those options will be used for SSH connections check as well as added to generated Ansible inventory so that other tools can use it.

feat: configurable ssh options

---

src/mrack/providers/openstack.py
tests/unit/test_openstack.py

This modification will catch the Exception, to free all hosts and wait for quota to be available again

fix: Handle 403 AuthError (out of quota) in openstack provisioning

---

src/mrack/outputs/pytest_mh.py
src/mrack/outputs/utils.py
tests/unit/test_output_utils.py
tests/unit/test_pytest_mh.py

pytest-mh configuration may contain nested dictionary, specifying
username or password in pytest_mh section will result in overriding
the host option, i.e.:
```
pytest_mh:
ssh:
username: tuser
password: tuserpassword
```
will generate wrong configuration where ssh/host is not set.
This patch makes sure that the ssh key is merged instead of overwritten.

feat(outputs): merge nested dictionary instead of overriding it

---

.packit.yaml

Add internal tests for pre-defined use cases from
internal repository with the specifications.
These tests are switched by using MRACK_TEST_CASE
environment variable with a test that needs to be
specified in the internal repository.

chore(Packit): Add internalt tests per pull request

---

.github/workflows/test-and-release.yml

Version 7.33.1 of python-semantic-release action is failing in the container build. Updating action to this version will solve this issue.

chore: Bump python-semantic-release to v7.34.4

---

.github/workflows/test-and-release.yml
pyproject.toml

Due to latest changes to python semantic release
PyPI release is no longer supported and the separate action (https://github.com/pypa/gh-action-pypi-publish) is recomended to use while releasing to PyPI.
For the trusted publishing we had to set up the PyPI account owning mrack to trust neoave/mrack repository which I did and set up the actions jobs to build
the python package and trigger a truster build.
As an addition i have extracted copr to separate job.

chore(release): Add PyPI action & extract copr step

---

.github/workflows/test-and-release.yml

actions/checkout checks out the latest commit at the time of the workflow trigger, 
hence any commit done during the workflow is not included. 
Fixing this to checkout the actual latest (release) commit.

chore(ci): Fix release workflow build step checking out wrong commit

---

src/mrack/providers/openstack.py
tests/unit/test_openstack.py

This will save a manual step for the users when setting up clouds.yaml file, as auth_url field is usually generated without specifying the version.
Version specification is needed by asyncopenstackclient libray

feat(openstack): Append API version to auth_url in credentials

---

src/mrack/providers/openstack.py
tests/unit/test_openstack.py

await call for _curate_auth_url missing in session creation which caused regression.
function _curate_auth_url changed to non-async, tests updated to reflect the same

fix: curate_auth_url func changed to non-async

---

mrack.spec
requirements.txt

This dependency was observed missing when installing mrack as a dependency in another python project

feat: Add async_timeout dependency to requirements.txt

---

src/mrack/providers/beaker.py

fix the tmt clean guest issue: https://github.com/teemtee/tmt/issues/2796

fix: prefix job_id with J: for _get_recipe_info

---

src/mrack/providers/beaker.py
src/mrack/transformers/beaker.py
tests/integration/conftest.py
tests/integration/test_actions.py
tests/unit/conftest.py
tests/unit/test_ansible_inventory.py
tests/unit/test_beaker.py
tests/unit/test_beaker_transformer.py
tests/unit/test_pytest_mh.py
tests/unit/test_pytest_multihost.py

**fix(beaker): suppress 10_avc_check restraint plugin**
It has happpened that this plugin sometimes ran after the dummy task, it reported fail
that there was some AVC (probabaly from other thing) which then failed the job and thus
mrack treated this as a provisioning failure.
This patch instructs restraint to not run this plugin and thus avoid this situation.
**test: speed-up tests by mocking gethostbyaddr**
Tests that are using mrack outputs are slowed down by
socker.gethostbyaddr for adhoc IP addresses. This resolution mostly
fails and the test is slow (multiple seconds timeout for single IP).
With this, all python tests are executed within 1.5s.
**Notes**
The other patch  was created so that I can run the tests locally effectively.

fix(beaker): suppress 10_avc_check restraint plugin

---

.github/workflows/pre-commit.yml
.github/workflows/test-and-release.yml

Due to warnings shown in https://github.com/neoave/mrack/actions/runs/9302766806
It updates actions to new version with Node 20

chore: Update deprecated actions

---

src/mrack/outputs/pytest_mh.py
tests/unit/test_pytest_mh.py

pytest-mh implemented a generic connection interface so one
can choose between ssh, podman and docker. This introduced
a breaking change in the configuration.
The `ssh` field was changed to a generic `conn` field that
specifies the connection type.
More information can be found in the pytest-mh pull request.
Depends on:
* https://github.com/next-actions/pytest-mh/pull/67

feat: update pytest-mh output to work with latest version

---

docs/conf.py
setup.py
src/mrack/data/provisioning-config.yaml
src/mrack/data/seccomp.json
src/mrack/providers/podman.py
src/mrack/providers/utils/podman.py
src/mrack/transformers/podman.py

Amending some changes as per comments in PR #298 and adjust commit messages

feat: Refine #298

---

.packit.yaml

Use epel major version instead of epel-all to avoid releasing to minor branches (e.g. epel10.0) and drop epel8 (supported dropped in tmt)

chore(packit): Update epel spec for fedora propose upstream

---

.github/workflows/test-and-release.yml

Python release was failing due to a dep issue when building python-semantic-release action image. e.g. https://github.com/neoave/mrack/actions/runs/16966276988
Upgrading to 10.3.1 to fix it
Breaking changes don't affect our implementation.
Fixes: https://github.com/neoave/mrack/issues/321

chore: Bump python-semantic-release to fix release issue

---

src/mrack/providers/beaker.py
src/mrack/transformers/beaker.py
tests/unit/test_beaker.py
tests/unit/test_beaker_transformer.py

Add support to pass watchdog panic="ignore" in Beaker recipe.
Add unit tests for beaker-watchdog panic=ignore recipe option.
I have tested this branch with the soon-to-be-proposed `tmt` changes.
Fixes: `tmt` issue [#4004](https://github.com/teemtee/tmt/issues/4004).
Assisted by: Cursor AI

feat: Add support to pass watchdog panic="ignore"
